### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by ConnectGrid** [amaccis/php-stemmer#1]
Do you want a pull request to support PHP 8.0, or is this already in the works? Thanks!

**Comment by amaccis** [comment]
Hi @ConnectGrid 
I was thinking of working on it but I didn't yet, so a pull request would be good!
Thanks!

**Comment by amaccis** [comment]
Hi @ConnectGrid, I've just published a new release that supports PHP 8, so I'm closing this issue.
