### ISSUE TITLE
stemmer, utf8_encode($word));

### ISSUE THREAD

**Issue by persuader** [amaccis/php-stemmer#4]
Hi. Thanks for your work. 

When i try to use the library with Portuguese or Spanish language the utf8_encode funcion in function stemWord breaks letters with accents and "special" characters and the output is garbage - i already send the text encoded as UTF-8. 

When i remove the utf_encode function everything works as expected. - something like - 

$stem = $this->libstemmer->sbStemmerStem($this->stemmer, $word);

**Comment by amaccis** [comment]
Hi @persuader. Can you provide me a sample word? Portuguese or Spanish or both. I would like to fix it and write a unit test.

**Comment by persuader** [comment]
Portuguese: 

with utf8_encode 

atribuição -> atribuiÃ§Ã£

obrigações -> obrigaÃ§Ãµ

without utf8_encode - 

atribuição -> atribuiçã

obrigações -> obrig

**Comment by amaccis** [comment]
Hi @persuader. 
So, taking your advice, I chose to take for granted that the input is UTF-8, let's see.
I've just released a new minor version (1.1.1) that fixes the issue and adds your cases to the functional tests.
I'm closing this because it should be solved, but feel free to re open it if not.
